name: zarf_mobile
description: Zarf mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^13.2.5
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  uuid: ^4.4.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
